#!/bin/bash

set -e

cd
if [ -d "$HOME/.cfg" ]; then
	echo "> Dotfiles already installed in ~/.cfg!"
	exit 1
fi
git clone --bare git@github.com:creikey/dotfiles.git $HOME/.cfg
function config {
   /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME $@
}
mkdir -p .config-backup
set +e
config checkout
if [ $? = 0 ]; then
	set -e
	echo "> Checked out config...";
else
	set -e
	echo "> Backing up pre-existing dot files...";
	config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} sh -c 'install -Dv {} .config-backup/{}; rm {}'
fi
echo "> Dot files backed up"
config checkout
config config status.showUntrackedFiles no
echo "> Success!"
